function [t] = calc_t_analytical(theta)

    [theta1, theta2, theta3, theta4, theta5, theta6, theta7] = thetamap(theta);
    t = zeros(4, 4);
    
    l1 = 14.2;
    l2 = 1.8;
    l3 = 14.5;
    l5 = 29.5;
    
    t(1, 1) = cos(theta1)*cos(theta2)*cos(theta3)*cos(theta4)*cos(theta5)*cos(theta6)*cos(theta7)+cos(theta1)*cos(theta2)*cos(theta6)*cos(theta7)*sin(theta3)*sin(theta5)+cos(theta1)*cos(theta5)*cos(theta6)*cos(theta7)*sin(theta2)*sin(theta4)+cos(theta4)*cos(theta5)*cos(theta6)*cos(theta7)*sin(theta1)*sin(theta3)-cos(theta3)*cos(theta6)*cos(theta7)*sin(theta1)*sin(theta5)+cos(theta1)*cos(theta2)*cos(theta3)*cos(theta7)*sin(theta4)*sin(theta6)-cos(theta1)*cos(theta4)*cos(theta7)*sin(theta2)*sin(theta6)+cos(theta7)*sin(theta1)*sin(theta3)*sin(theta4)*sin(theta6)+cos(theta1)*cos(theta2)*cos(theta3)*cos(theta4)*sin(theta5)*sin(theta7)-cos(theta1)*cos(theta2)*cos(theta5)*sin(theta3)*sin(theta7)+cos(theta1)*sin(theta2)*sin(theta4)*sin(theta5)*sin(theta7)+cos(theta4)*sin(theta1)*sin(theta3)*sin(theta5)*sin(theta7)+cos(theta3)*cos(theta5)*sin(theta1)*sin(theta7);
    t(1, 2) = cos(theta1)*cos(theta2)*cos(theta3)*cos(theta4)*cos(theta5)*sin(theta6)+cos(theta1)*cos(theta2)*sin(theta3)*sin(theta5)*sin(theta6)+cos(theta1)*cos(theta5)*sin(theta2)*sin(theta4)*sin(theta6)+cos(theta4)*cos(theta5)*sin(theta1)*sin(theta3)*sin(theta6)-cos(theta3)*sin(theta1)*sin(theta5)*sin(theta6)-cos(theta1)*cos(theta2)*cos(theta3)*cos(theta6)*sin(theta4)+cos(theta1)*cos(theta4)*cos(theta6)*sin(theta2)-cos(theta6)*sin(theta1)*sin(theta3)*sin(theta4);
    t(1, 3) = cos(theta1)*cos(theta2)*cos(theta3)*cos(theta4)*cos(theta5)*cos(theta6)*sin(theta7)+cos(theta1)*cos(theta2)*cos(theta6)*sin(theta3)*sin(theta5)*sin(theta7)+cos(theta1)*cos(theta5)*cos(theta6)*sin(theta2)*sin(theta4)*sin(theta7)+cos(theta4)*cos(theta5)*cos(theta6)*sin(theta1)*sin(theta3)*sin(theta7)-cos(theta3)*cos(theta6)*sin(theta1)*sin(theta5)*sin(theta7)+cos(theta1)*cos(theta2)*cos(theta3)*sin(theta4)*sin(theta6)*sin(theta7)-cos(theta1)*cos(theta4)*sin(theta2)*sin(theta6)*sin(theta7)+sin(theta1)*sin(theta3)*sin(theta4)*sin(theta6)*sin(theta7)-cos(theta1)*cos(theta2)*cos(theta3)*cos(theta4)*cos(theta7)*sin(theta5)+cos(theta1)*cos(theta2)*cos(theta5)*cos(theta7)*sin(theta3)-cos(theta1)*cos(theta7)*sin(theta2)*sin(theta4)*sin(theta5)-cos(theta4)*cos(theta7)*sin(theta1)*sin(theta3)*sin(theta5)-cos(theta3)*cos(theta5)*cos(theta7)*sin(theta1);
    t(1, 4) = l5*cos(theta1)*cos(theta2)*cos(theta3)*sin(theta4)-l5*cos(theta1)*cos(theta4)*sin(theta2)-l3*cos(theta1)*sin(theta2)+l5*sin(theta1)*sin(theta3)*sin(theta4)-l2*sin(theta1);
    t(2, 1) = cos(theta2)*cos(theta3)*cos(theta4)*cos(theta5)*cos(theta6)*cos(theta7)*sin(theta1)+cos(theta2)*cos(theta6)*cos(theta7)*sin(theta1)*sin(theta3)*sin(theta5)+cos(theta5)*cos(theta6)*cos(theta7)*sin(theta1)*sin(theta2)*sin(theta4)-cos(theta1)*cos(theta4)*cos(theta5)*cos(theta6)*cos(theta7)*sin(theta3)+cos(theta1)*cos(theta3)*cos(theta6)*cos(theta7)*sin(theta5)+cos(theta2)*cos(theta3)*cos(theta7)*sin(theta1)*sin(theta4)*sin(theta6)-cos(theta4)*cos(theta7)*sin(theta1)*sin(theta2)*sin(theta6)-cos(theta1)*cos(theta7)*sin(theta3)*sin(theta4)*sin(theta6)+cos(theta2)*cos(theta3)*cos(theta4)*sin(theta1)*sin(theta5)*sin(theta7)-cos(theta2)*cos(theta5)*sin(theta1)*sin(theta3)*sin(theta7)+sin(theta1)*sin(theta2)*sin(theta4)*sin(theta5)*sin(theta7)-cos(theta1)*cos(theta4)*sin(theta3)*sin(theta5)*sin(theta7)-cos(theta1)*cos(theta3)*cos(theta5)*sin(theta7);
    t(2, 2) = cos(theta2)*cos(theta3)*cos(theta4)*cos(theta5)*sin(theta1)*sin(theta6)+cos(theta2)*sin(theta1)*sin(theta3)*sin(theta5)*sin(theta6)+cos(theta5)*sin(theta1)*sin(theta2)*sin(theta4)*sin(theta6)-cos(theta1)*cos(theta4)*cos(theta5)*sin(theta3)*sin(theta6)+cos(theta1)*cos(theta3)*sin(theta5)*sin(theta6)-cos(theta2)*cos(theta3)*cos(theta6)*sin(theta1)*sin(theta4)+cos(theta4)*cos(theta6)*sin(theta1)*sin(theta2)+cos(theta1)*cos(theta6)*sin(theta3)*sin(theta4);
    t(2, 3) = cos(theta2)*cos(theta3)*cos(theta4)*cos(theta5)*cos(theta6)*sin(theta1)*sin(theta7)+cos(theta2)*cos(theta6)*sin(theta1)*sin(theta3)*sin(theta5)*sin(theta7)+cos(theta5)*cos(theta6)*sin(theta1)*sin(theta2)*sin(theta4)*sin(theta7)-cos(theta1)*cos(theta4)*cos(theta5)*cos(theta6)*sin(theta3)*sin(theta7)+cos(theta1)*cos(theta3)*cos(theta6)*sin(theta5)*sin(theta7)+cos(theta2)*cos(theta3)*sin(theta1)*sin(theta4)*sin(theta6)*sin(theta7)-cos(theta4)*sin(theta1)*sin(theta2)*sin(theta6)*sin(theta7)-cos(theta1)*sin(theta3)*sin(theta4)*sin(theta6)*sin(theta7)-cos(theta2)*cos(theta3)*cos(theta4)*cos(theta7)*sin(theta1)*sin(theta5)+cos(theta2)*cos(theta5)*cos(theta7)*sin(theta1)*sin(theta3)-cos(theta7)*sin(theta1)*sin(theta2)*sin(theta4)*sin(theta5)+cos(theta1)*cos(theta4)*cos(theta7)*sin(theta3)*sin(theta5)+cos(theta1)*cos(theta3)*cos(theta5)*cos(theta7);
    t(2, 4) = l5*cos(theta2)*cos(theta3)*sin(theta1)*sin(theta4)-l5*cos(theta4)*sin(theta1)*sin(theta2)-l3*sin(theta1)*sin(theta2)-l5*cos(theta1)*sin(theta3)*sin(theta4)+l2*cos(theta1);
    t(3, 1) = cos(theta3)*cos(theta4)*cos(theta5)*cos(theta6)*cos(theta7)*sin(theta2)+cos(theta6)*cos(theta7)*sin(theta2)*sin(theta3)*sin(theta5)-cos(theta2)*cos(theta5)*cos(theta6)*cos(theta7)*sin(theta4)+cos(theta3)*cos(theta7)*sin(theta2)*sin(theta4)*sin(theta6)+cos(theta2)*cos(theta4)*cos(theta7)*sin(theta6)+cos(theta3)*cos(theta4)*sin(theta2)*sin(theta5)*sin(theta7)-cos(theta5)*sin(theta2)*sin(theta3)*sin(theta7)-cos(theta2)*sin(theta4)*sin(theta5)*sin(theta7);
    t(3, 2) = cos(theta3)*cos(theta4)*cos(theta5)*sin(theta2)*sin(theta6)+sin(theta2)*sin(theta3)*sin(theta5)*sin(theta6)-cos(theta2)*cos(theta5)*sin(theta4)*sin(theta6)-cos(theta3)*cos(theta6)*sin(theta2)*sin(theta4)-cos(theta2)*cos(theta4)*cos(theta6);
    t(3, 3) = cos(theta3)*cos(theta4)*cos(theta5)*cos(theta6)*sin(theta2)*sin(theta7)+cos(theta6)*sin(theta2)*sin(theta3)*sin(theta5)*sin(theta7)-cos(theta2)*cos(theta5)*cos(theta6)*sin(theta4)*sin(theta7)+cos(theta3)*sin(theta2)*sin(theta4)*sin(theta6)*sin(theta7)+cos(theta2)*cos(theta4)*sin(theta6)*sin(theta7)-cos(theta3)*cos(theta4)*cos(theta7)*sin(theta2)*sin(theta5)+cos(theta5)*cos(theta7)*sin(theta2)*sin(theta3)+cos(theta2)*cos(theta7)*sin(theta4)*sin(theta5);
    t(3, 4) = l5*cos(theta3)*sin(theta2)*sin(theta4)+l5*cos(theta2)*cos(theta4)+l3*cos(theta2)+l1;
    t(4, 1) = 0;
    t(4, 2) = 0;
    t(4, 3) = 0;
    t(4, 4) = 1;
    
    
    
end